machine: 
  node:
    version: 
      v0.10.33
  hosts: 
    main-srv: 188.166.44.244

dependencies:
  pre:
    - npm install -g jasmine-node

test: 
  override: 
    - jasmine-node ./nodeapp/test/ 

deployment: 
  prod: 
    branch: master
    commands: 
      - ssh deploy@main-srv 'cd youdo && git fetch --all && git reset --hard origin/master'
      - ssh deploy@main-srv 'cd youdo/nodeapp npm install && pm2 restart app/app.js'