machine: 
  node:
    version: 
      v0.10.33
  hosts: 
    main-srv: 188.166.44.244

dependencies:
  pre:
    - npm install -g jasmine-node
    - echo "create database youdo; grant all privileges on youdo.* to 'youdoadmin'@'%' identified by 'youdopassword'" | mysql -u root 
    - mysql -u root youdo < ./sql_schema/users.sql  

test: 
  override: 
    - jasmine-node --verbose --forceexit ./test/ 

deployment: 
  prod: 
    branch: master
    commands: 
      - ssh deploy@main-srv 'cd youdo && git fetch --all && git reset --hard origin/master'
      - ssh deploy@main-srv 'cd youdo && npm install && pm2 delete all && pm2 start processes.json' 